name: pdfrx
description: pdfrx is a rich and fast PDF viewer implementation built on the top of pdfium. The plugin supports Android, iOS, Windows, macOS, Linux, and Web.
version: 1.0.6
homepage: https://github.com/espresso3389/pdfrx

environment:
  sdk: '>=3.3.0-76.0.dev <4.0.0'
  flutter: '>=3.19.0-0.4.pre'

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  js: ^0.7.0
  path: ^1.8.3
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  synchronized: ^3.1.0+1
  url_launcher: ^6.2.4
  vector_math: ^2.1.4
  web: ^0.4.2

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
      windows:
        ffiPlugin: true

# dart run ffigen
ffigen:
  output:
    bindings: 'lib/src/pdfium/pdfium_bindings.dart'
  headers:
    entry-points:
      - 'example/build/windows/x64/.lib/latest/include/fpdfview.h'
      - 'example/build/windows/x64/.lib/latest/include/fpdf_annot.h'
      - 'example/build/windows/x64/.lib/latest/include/fpdf_text.h'
      - 'example/build/windows/x64/.lib/latest/include/fpdf_doc.h'
      - 'example/build/windows/x64/.lib/latest/include/fpdf_edit.h'
      - 'example/build/windows/x64/.lib/latest/include/fpdf_formfill.h'
    include-directives:
      - 'example/build/windows/x64/.lib/latest/include/**'
  name: 'pdfium'
